name: Weibo SuperTopic Check-in

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 0 点 UTC 运行（北京时间 8 点）
  workflow_dispatch:      # 手动触发

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      env:
        WEIBO_COOKIE: ${{ secrets.WEIBO_COOKIE }}
        MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
        MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
        MAIL_AUTH_CODE: ${{ secrets.MAIL_AUTH_CODE }}
      run: python weibo_checkin.py
